name: js-lint

on:
  pull_request:
    paths:
      - ".github/workflows/js-lint.yml"
      - "client/src/**/*.js"
      - "client/src/**/*.jsx"
      - "client/src/**/*.ts"
      - "client/src/**/*.tsx"
      - "api/**/*"

jobs:
  JsLint:
    name: Lint javascript and typescript files
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.changed_files != 0 }} # Ensure the job runs only if there are changes in the PR

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Ensures the entire repo is checked out (including tags)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache and install node_modules
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --recursive
        working-directory: client

      - name: GitHub Action for Javascript linting
        run: pnpm lint:fix
        working-directory: client
