name: js-test

on:
  pull_request:
    paths:
      - ".github/workflows/js-test.yml"
      - "client/**/*.js"
      - "client/**/*.jsx"
      - "client/**/*.ts"
      - "client/**/*.tsx"
      - "server/**/*.py"

jobs:
  JsTest:
    name: Run javascript tests
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Ensures the entire repo is checked out (including tags)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache and install node_modules
      - name: pnpm install dependencies with caching
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]

      - name: GitHub Action for Javascript testing
        run: pnpm test
        working-directory: client
