name: js-checks

on:
  pull_request:
    paths:
      - '.github/workflows/js-checks.yml'
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.ts'
      - '**/*.tsx'

jobs:
  JsChecks:
    name: Run Javascript linting, type checks and tests
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Ensures the entire repo is checked out (including tags)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache and install node_modules
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --recursive

        # Run linting and testing scripts
      - name: GitHub Action for Javascript linting
        run: pnpm lint:fix

      - name: GitHub Action for TypeScript type checking
        run: pnpm type-check

      - name: GitHub Action for Javascript testing
        run: pnpm test
